"""
One-off script: drafts the PE-authored content (TDS, PCC, Schedule of
Requirements, Qualification Criteria) for a Bangladesh e-GP e-PG4 [OTM(ICT)]
Standard Tender Document -- Procurement of Goods, International Competitive
Tendering, one-stage one-envelope, per PPR 2025.

This is NOT a full tender document: under PPR 2025 / e-GP Guidelines 2025,
the Instructions to Tenderer (ITB) and General Conditions of Contract (GCC)
are fixed system templates owned by BPPA and are not authored by the PE.
[eGP_Guidelines.pdf | page 19-20]. This draft covers only the sections the
Procuring Entity fills in.
"""
from docx import Document
from docx.shared import Pt, Cm, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
import datetime

doc = Document()

# ---- base styles ----
style = doc.styles["Normal"]
style.font.name = "Calibri"
style.font.size = Pt(11)

def set_col_widths(table, widths_cm):
    for row in table.rows:
        for cell, w in zip(row.cells, widths_cm):
            cell.width = Cm(w)

def shade_cell(cell, color_hex):
    tcPr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"), color_hex)
    tcPr.append(shd)

def h1(text):
    p = doc.add_heading(text, level=1)
    return p

def h2(text):
    return doc.add_heading(text, level=2)

def body(text, bold=False, italic=False):
    p = doc.add_paragraph()
    r = p.add_run(text)
    r.bold = bold
    r.italic = italic
    return p

def note(text):
    p = doc.add_paragraph()
    r = p.add_run(text)
    r.italic = True
    r.font.color.rgb = RGBColor(0x99, 0x00, 0x00)
    return p

# ================= COVER =================
title = doc.add_paragraph()
title.alignment = WD_ALIGN_PARAGRAPH.CENTER
r = title.add_run("STANDARD TENDER DOCUMENT (STD) e-PG4 [OTM(ICT)]")
r.bold = True
r.font.size = Pt(16)

sub = doc.add_paragraph()
sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
r = sub.add_run("Procurement of Goods \u2014 International Competitive Tendering (ICT)\nOne-Stage One-Envelope Method \u2014 Under Public Procurement Rules (PPR) 2025")
r.font.size = Pt(12)

pe = doc.add_paragraph()
pe.alignment = WD_ALIGN_PARAGRAPH.CENTER
r = pe.add_run("Procuring Entity: NIKDU")
r.bold = True
r.font.size = Pt(13)

goods = doc.add_paragraph()
goods.alignment = WD_ALIGN_PARAGRAPH.CENTER
r = goods.add_run("Procurement of Hemodialysis Machines with UPS (1,030 units)\nfor Kidney (Renal) Patient Care")
r.font.size = Pt(12)

doc.add_paragraph()
note(
    "SCOPE NOTE: Under PPR 2025 / e-GP Guidelines 2025, the Instructions to Tenderer (ITB), "
    "General Conditions of Contract (GCC) and Tender/Contract Forms for e-PG4 are fixed "
    "dynamic-form templates generated by the e-GP system and are not authored by the "
    "Procuring Entity [eGP_Guidelines.pdf | page 19-20]. This draft covers only the sections "
    "the PE fills in when preparing the package on the portal: the Tender Data Sheet (TDS), "
    "Particular Conditions of Contract (PCC), Schedule of Requirements / Technical "
    "Specification, and Qualification Criteria. Bracketed [ITEMS IN CAPS] are placeholders "
    "requiring PE decision or NIKDU-specific input not yet supplied."
)
note(
    "FORM-SERIES CAVEAT: This is an International Competitive Tendering (ICT) package, so "
    "the applicable Standard Tender Document is e-PG4 [OTM(ICT)], per [egp_new_features.md | "
    "page 163]. The Bangladesh e-GP knowledge base used to ground this draft only contains "
    "retrievable form text labeled as the PG3-series (e.g., \"PG3-10\", \"Form PG3-2\") from "
    "PPR2025.pdf pages 242-249 — no e-PG4-specific form text was retrievable. Declaration "
    "content below (tender validity, tender security, eligibility, discount) was drafted from "
    "that PG3-series text as the closest available template language, since the underlying "
    "PPR 2025 legal obligations are the same regardless of STD. The ACTUAL e-PG4 form set and "
    "form numbering must be pulled directly from the e-GP portal when NIKDU creates this "
    "package — do not submit or reference PG3-numbered forms for this international tender."
)
doc.add_page_break()

# ================= COVER NOTE =================
h1("Cover Note — Read Before Circulating")
body(
    "This document is a working draft prepared to accelerate NIKDU's e-PG4 [OTM(ICT)] tender "
    "package preparation. It is NOT ready for publication on the e-GP portal. Sections below "
    "are marked by how they were sourced:",
    bold=True,
)

t0 = doc.add_table(rows=1, cols=3)
t0.style = "Light Grid Accent 1"
hdr = t0.rows[0].cells
for i, txt in enumerate(["Section", "Status", "What NIKDU Must Do"]):
    hdr[i].text = txt
    for p in hdr[i].paragraphs:
        for r in p.runs:
            r.bold = True

cover_rows = [
    ("Section 1 — IFT Key Particulars", "Confirmed (NIKDU-supplied data)", "No action — values as provided"),
    ("Section 2 — TDS (Tender Validity, Tender Security)", "Confirmed (NIKDU-supplied: 150 days, 2% of OCE) — BUT base mismatch flagged vs. real precedent", "NICVD FY2024-25 precedent uses 3% of quoted value (Tenderer's bid), not % of OCE. Confirm intended base before publication."),
    ("Section 2 — TDS (Performance Security 10%)", "AI-SUGGESTED, not KB-verified", "Confirm actual percentage against Schedule II of PPR 2025 (KB does not contain this table)"),
    ("Section 3 — Schedule of Requirements (phasing)", "AI-suggested even split of 180 days", "Replace with NIKDU's actual phasing plan"),
    ("Appendix A — Hospital Delivery List", "AI-SUGGESTED, unverified", "Verify every site's actual readiness (space, power, RO water, dialysis capacity) and confirm/replace the list; assign real per-hospital unit counts"),
    ("Section 4 — Technical Specification", "AI-SUGGESTED placeholder, generic", "MUST be replaced with the Technical Specification Committee's approved version before any further use — patient-safety relevant"),
    ("Section 5 — Qualification Criteria (declarations)", "Grounded in PPR 2025 / e-GP Guidelines", "No action — standard legal declarations"),
    ("Section 5 — Qualification Criteria (numeric thresholds)", "Benchmarked against a real comparable tender (NICVD FY2024-25), not PPR-2025-verified", "TEC to set actual BDT/count thresholds using this structure — wrong figures risk unlawfully restricting or under-qualifying competition"),
    ("Section 6 — PCC (Inspection, Warranty, Payment, LD)", "AI-SUGGESTED defaults", "Confirm against NIKDU's standard contract terms and PPR 2025 requirements before publication"),
    ("Section 2 — Source of Fund / Eligible Countries / Domestic Preference", "Confirmed (NIKDU-supplied)", "No action — values as provided"),
    ("Section 5 & 7 — Declaration/Form content", "Drafted from PG3-series KB text (National Competitive Tendering), NOT e-PG4 (International)", "This is an ICT package — pull the actual e-PG4 form set and form numbers from the e-GP portal; do not use PG3-numbered forms. See Form-Series Caveat below."),
]
for a, b_, c_ in cover_rows:
    row = t0.add_row().cells
    row[0].text = a
    row[1].text = b_
    row[2].text = c_
set_col_widths(t0, [5.0, 5.0, 6.0])

doc.add_paragraph()
note(
    "In short: treat every AI-SUGGESTED row above as a placeholder to validate, not a final "
    "answer. This draft accelerates document preparation; it does not substitute for NIKDU's "
    "TEC, biomedical engineering, legal, and procurement sign-off."
)

doc.add_page_break()

# ================= SECTION 1: IFT SUMMARY =================
h1("Section 1 \u2014 Invitation for Tender (IFT): Key Particulars")
body(
    "The IFT itself is generated by the e-GP system from the package data below when NIKDU "
    "publishes the tender. The particulars that will populate it are:"
)

t = doc.add_table(rows=1, cols=2)
t.style = "Light Grid Accent 1"
t.alignment = WD_TABLE_ALIGNMENT.CENTER
hdr = t.rows[0].cells
hdr[0].text = "Particular"
hdr[1].text = "Detail"
for c in hdr:
    for p in c.paragraphs:
        for r in p.runs:
            r.bold = True

ift_rows = [
    ("Procuring Entity", "NIKDU"),
    ("Procurement Method", "Open Tendering Method (OTM) \u2014 International Competitive Tendering (ICT)"),
    ("Tendering Procedure", "One-Stage One-Envelope"),
    ("Standard Tender Document (STD)", "e-PG4 [OTM(ICT)]"),
    ("Goods to be Procured", "Hemodialysis Machine with UPS"),
    ("Quantity", "1,030 units (phased: 300 / 400 / 330 \u2014 see Section 3)"),
    ("Purpose", "To serve kidney (renal) disease patients under NIKDU's care network"),
    ("Official Cost Estimate (OCE)", "BDT 26,750.00 lakh (BDT 2,675,000,000 / approx. BDT 267.5 crore)"),
    ("Delivery Period", "180 days from contract signing, in three phases (see Section 3)"),
    ("Delivery Locations", "Multiple public hospitals across Bangladesh — suggested list at Appendix A (draft, pending NIKDU confirmation)"),
    ("Minimum Tender Preparation Time", "42 days from date of publication of advertisement in the e-GP System (international tendering minimum) [eGP_Guidelines.pdf | page 52]"),
    ("Source of Fund", "Government of Bangladesh (GoB)"),
]
for a, b_ in ift_rows:
    row = t.add_row().cells
    row[0].text = a
    row[1].text = b_
set_col_widths(t, [5.5, 10.5])

doc.add_paragraph()

# ================= SECTION 2: TDS =================
doc.add_page_break()
h1("Section 2 \u2014 Tender Data Sheet (TDS)")
body(
    "The TDS modifies and supplements the fixed ITB clauses [eGP_Guidelines.pdf | page 19]. "
    "Entries below follow the standard e-PG4 TDS clause numbering pattern (ITT Sub-Clause "
    "references are placeholders \u2014 actual clause numbers are assigned by the system template)."
)

t2 = doc.add_table(rows=1, cols=3)
t2.style = "Light Grid Accent 1"
hdr = t2.rows[0].cells
hdr[0].text = "ITT Sub-Clause"
hdr[1].text = "TDS Entry"
hdr[2].text = "Basis / Note"
for c in hdr:
    for p in c.paragraphs:
        for r in p.runs:
            r.bold = True

tds_rows = [
    ("Name of Procuring Entity", "NIKDU", ""),
    ("Brief Description of Goods", "Hemodialysis Machine with UPS, 1,030 units", ""),
    ("Tender Validity Period", "150 days from the date of Tender opening", "Tender remains valid/binding for the period stated here [PPR2025.pdf | page 243]; set by NIKDU"),
    ("Tender Security \u2014 Amount", "BDT 53,500,000 (BDT 535.00 lakh / approx. BDT 5.35 crore) \u2014 2% of the Official Cost Estimate (BDT 26,750.00 lakh)", "PPR 2025 does not fix a universal percentage in the retrieved text; 2% set by NIKDU. BASE MISMATCH FLAG: the NICVD FY2024-25 comparable tender sets Tender Security at 3% of the Tenderer's own quoted price (ITT 31.1), not a percentage of the OCE. NIKDU's 2%-of-OCE is a different base (fixed amount, known in advance) than NICVD's 3%-of-quoted-value (variable, set per Tenderer's bid). Both are valid mechanics under PPR generally; TEC should confirm which base NIKDU intends before publication, since the two are not directly comparable percentages."),
    ("Tender Security \u2014 Form", "Pay Order / Bank Draft / Bank Guarantee (Tenderer's choice, per system options)", "[PPR2025.pdf | page 243]"),
    ("Tender Security \u2014 Validity", "28 days beyond the Tender Validity Date (i.e., through day 178)", "[PPR2025.pdf | page 243, 247]"),
    ("Performance Security \u2014 Amount / Form", "AI-suggested draft: 10% of the Contract Price, as an irrevocable, unconditional Bank Guarantee", "PPR 2025 ties the actual amount to the threshold in Schedule II [eGP_Guidelines.pdf | page 39], which is not in the retrieved KB text \u2014 NIKDU/TEC must verify the exact figure against Schedule II before finalizing; 10% shown here is common practice, not a KB-sourced figure"),
    ("Performance Security \u2014 Validity", "28 days beyond the date of completion of performance obligations", "[PPR2025.pdf | page 243]"),
    ("Delivery Period", "180 days from contract signing date, phased delivery", "See Section 3 for phase breakdown"),
    ("Domestic Preference Applicable", "Yes \u2014 15% Domestic Preference applied automatically (cannot be changed)", "[egp_new_features.md | page 163]"),
    ("Joint Venture (JV) Participation", "Not allowed", "JV is not permitted under the e-PG4 [OTM(ICT)] STD [egp_new_features.md | page 163]"),
    ("Significantly Low-Priced Tender (SLT) Threshold", "Quoted prices more than 10% below the Official Cost Estimate are treated as financially non-responsive", "[egp_new_features.md | page 12]"),
    ("Eligible Countries", "All countries are eligible, except Israel", "Per NIKDU instruction"),
]
for a, b_, c_ in tds_rows:
    row = t2.add_row().cells
    row[0].text = a
    row[1].text = b_
    row[2].text = c_
set_col_widths(t2, [4.5, 7.0, 4.5])

# ================= SECTION 3: SCHEDULE OF REQUIREMENTS =================
doc.add_page_break()
h1("Section 3 \u2014 Schedule of Requirements")

t3 = doc.add_table(rows=1, cols=5)
t3.style = "Light Grid Accent 1"
hdr = t3.rows[0].cells
for i, txt in enumerate(["Phase", "Quantity (units)", "Delivery Deadline", "Delivery Location", "Remarks"]):
    hdr[i].text = txt
    for p in hdr[i].paragraphs:
        for r in p.runs:
            r.bold = True

sched_rows = [
    ("Phase 1", "300", "Within 60 days of contract signing (indicative \u2014 PE to confirm split of the 180-day period)", "Dhaka Division hospitals \u2014 see Appendix A", "Includes installation & commissioning per site"),
    ("Phase 2", "400", "Within 120 days of contract signing (indicative)", "Chattogram, Sylhet & Mymensingh Division hospitals \u2014 see Appendix A", "Includes installation & commissioning per site"),
    ("Phase 3", "330", "Within 180 days of contract signing", "Rajshahi, Khulna, Barishal & Rangpur Division hospitals \u2014 see Appendix A", "Includes installation & commissioning per site"),
    ("Total", "1,030", "180 days from contract signing", "Multiple hospitals, Bangladesh", ""),
]
for row_data in sched_rows:
    row = t3.add_row().cells
    for i, val in enumerate(row_data):
        row[i].text = val
set_col_widths(t3, [2.2, 2.5, 4.5, 4.0, 3.0])

note(
    "Phase-wise deadlines (60/120/180 days) are an indicative even split of the 180-day "
    "delivery period, and the phase-to-division mapping is a suggested geographic grouping "
    "(central Dhaka hub first, then regional divisions) \u2014 both pending NIKDU's actual phasing "
    "plan and confirmed hospital list; adjust before publication."
)

h2("Appendix A \u2014 Suggested Delivery Hospital List (Draft, Not Verified)")
note(
    "AI-SUGGESTED DRAFT \u2014 NOT SOURCED FROM THE e-GP KNOWLEDGE BASE. This list is drawn from "
    "general public knowledge of Bangladesh's major public medical college hospitals and "
    "district-level facilities with existing or plausible nephrology/dialysis services. It "
    "has NOT been verified against NIKDU's actual referral network, site readiness (space, "
    "power, water treatment/RO capacity), or each hospital's current dialysis unit capacity. "
    "NIKDU's logistics and clinical teams must confirm every site \u2014 including whether the "
    "named hospital actually has (or is being prepared to have) dialysis infrastructure to "
    "receive these machines \u2014 before this becomes part of the published tender."
)

t3b = doc.add_table(rows=1, cols=3)
t3b.style = "Light Grid Accent 1"
hdr = t3b.rows[0].cells
for i, txt in enumerate(["Phase / Region", "Hospital (suggested)", "Division"]):
    hdr[i].text = txt
    for p in hdr[i].paragraphs:
        for r in p.runs:
            r.bold = True

appendix_rows = [
    ("Phase 1", "National Institute of Kidney Diseases and Urology (NIKDU), Dhaka", "Dhaka"),
    ("Phase 1", "Dhaka Medical College Hospital", "Dhaka"),
    ("Phase 1", "Bangabandhu Sheikh Mujib Medical University (BSMMU)", "Dhaka"),
    ("Phase 1", "Sir Salimullah Medical College Mitford Hospital", "Dhaka"),
    ("Phase 1", "Shaheed Suhrawardy Medical College Hospital", "Dhaka"),
    ("Phase 1", "Kurmitola General Hospital", "Dhaka"),
    ("Phase 1", "Faridpur Medical College Hospital", "Dhaka"),
    ("Phase 2", "Chattogram Medical College Hospital", "Chattogram"),
    ("Phase 2", "Cumilla Medical College Hospital", "Chattogram"),
    ("Phase 2", "Cox's Bazar Medical College Hospital", "Chattogram"),
    ("Phase 2", "Noakhali General Hospital (Maijdee)", "Chattogram"),
    ("Phase 2", "Sylhet MAG Osmani Medical College Hospital", "Sylhet"),
    ("Phase 2", "Mymensingh Medical College Hospital", "Mymensingh"),
    ("Phase 3", "Rajshahi Medical College Hospital", "Rajshahi"),
    ("Phase 3", "Shaheed Ziaur Rahman Medical College Hospital, Bogura", "Rajshahi"),
    ("Phase 3", "Khulna Medical College Hospital", "Khulna"),
    ("Phase 3", "Jessore General Hospital", "Khulna"),
    ("Phase 3", "Sher-e-Bangla Medical College Hospital, Barishal", "Barishal"),
    ("Phase 3", "Rangpur Medical College Hospital", "Rangpur"),
    ("Phase 3", "M Abdur Rahim Medical College Hospital, Dinajpur", "Rangpur"),
]
for a, b_, c_ in appendix_rows:
    row = t3b.add_row().cells
    row[0].text = a
    row[1].text = b_
    row[2].text = c_
set_col_widths(t3b, [2.5, 9.5, 4.0])

note(
    "Per-hospital unit allocation is intentionally not specified here \u2014 precise counts should "
    "be set by NIKDU based on each site's confirmed patient load, existing machine count, and "
    "dialysis bay/infrastructure capacity, not assumed by this draft."
)

# ================= SECTION 4: TECHNICAL SPECIFICATIONS =================
doc.add_page_break()
h1("Section 4 \u2014 Technical Specification (AI-Suggested Draft \u2014 Pending Clinical Sign-Off)")
body("Item: Hemodialysis Machine with Uninterruptible Power Supply (UPS)")
note(
    "AI-SUGGESTED DRAFT \u2014 NOT SOURCED FROM THE e-GP KNOWLEDGE BASE. These are generic, "
    "commonly specified parameters for hospital-grade hemodialysis machines, not tied to any "
    "specific brand/model and not a substitute for clinical review. NIKDU's biomedical "
    "engineering and nephrology teams must validate, adjust, and formally approve every "
    "parameter (dialyzer compatibility, alarm thresholds, exact flow/UF ranges, certifications) "
    "before this is used in a real tender \u2014 incorrect specs here carry direct patient-safety "
    "and legal risk."
)

t4 = doc.add_table(rows=1, cols=2)
t4.style = "Light Grid Accent 1"
hdr = t4.rows[0].cells
hdr[0].text = "Parameter"
hdr[1].text = "Requirement"
for c in hdr:
    for p in c.paragraphs:
        for r in p.runs:
            r.bold = True

spec_rows = [
    ("Machine Type", "Microprocessor-controlled, volumetric ultrafiltration-control hemodialysis machine, single-patient, mobile (castor-mounted)"),
    ("Dialysis Modes Supported", "Standard bicarbonate hemodialysis (HD); sequential ultrafiltration (UF); isolated UF; hemodiafiltration (HDF) capability desirable but not mandatory unless NIKDU requires it"),
    ("Blood Pump Flow Rate", "Adjustable, approx. 0\u2013600 mL/min"),
    ("Dialysate Flow Rate", "Adjustable, approx. 300\u2013800 mL/min, with low-flow/flow-reduction option"),
    ("Ultrafiltration (UF) Control", "UF rate adjustable approx. 0\u20134,000 mL/hr; volumetric UF control with accuracy within \u00b12\u20133%"),
    ("Safety Monitoring", "Conductivity monitor, air/foam detector, blood-leak detector, arterial/venous pressure monitors, temperature control, with audible/visual alarms and auto blood-pump stop on fault"),
    ("Control Panel / Data", "Touch-screen interface with treatment data logging and (if available) connectivity for patient data export"),
    ("UPS Backup", "Integrated or bundled UPS providing minimum 30 minutes backup at full operating load, with automatic seamless switchover (no interruption to an in-progress treatment)"),
    ("Power Supply", "220\u2013240V AC, 50Hz, with surge/voltage-fluctuation protection suited to local grid conditions"),
    ("Water Treatment Compatibility", "Compatible with standard RO-treated water supply; feed water conductivity requirement to be confirmed with the offered water treatment system"),
    ("Consumables Compatibility", "Compatible with standard Luer-lock bloodlines and commercially available dialyzers (not single-source/proprietary-locked)"),
    ("Regulatory Approval", "CE marking or US FDA clearance (or equivalent recognized authority) for the offered model, plus DGDA (Directorate General of Drug Administration) import/medical-device clearance for use in Bangladesh"),
    ("Warranty", "Minimum 2 years comprehensive warranty from installation/commissioning date (NIKDU to confirm final period)"),
    ("Installation, Training & Commissioning", "Included, per delivery site, prior to acceptance \u2014 including biomedical staff and nursing staff training"),
    ("After-Sales Service / Spare Parts Availability", "Locally based or authorized service center with defined response time (e.g., within 48 hours of fault report); guaranteed spare-parts availability for a minimum period post-warranty (NIKDU to confirm, e.g., 5\u201310 years)"),
    ("Country of Origin / Manufacturer", "No restriction, provided the country of manufacture is an eligible country per the TDS (all countries except Israel)"),
]
for a, b_ in spec_rows:
    row = t4.add_row().cells
    row[0].text = a
    row[1].text = b_
set_col_widths(t4, [6.0, 10.0])

# ================= SECTION 5: QUALIFICATION CRITERIA =================
doc.add_page_break()
h1("Section 5 \u2014 Qualification / Eligibility Criteria (Standard, per PPR 2025)")
body(
    "Standard eligibility declarations required of every Tenderer for Goods procurement under "
    "PPR 2025, drafted from the PG3-series Letter of Tender text in the KB [PPR2025.pdf | page "
    "244] as a substantive proxy \u2014 see the Form-Series Caveat on the Cover Note; the actual "
    "e-PG4 Letter of Tender form should be used for submission:"
)
std_elig = [
    "The Tenderer, including any subcontractor, holds nationality from an eligible country.",
    "The Tenderer is submitting as a sole Tenderer (Joint Ventures are not permitted under this STD).",
    "The Tenderer declares whether it is a Government-owned entity and, if so, confirms it meets the applicable independence/commercial-operation requirements.",
    "The Tenderer has not been associated, directly or indirectly, with a consultant or entity that prepared the design, specifications, or other documents for this procurement.",
    "The Tenderer has examined the Tender Document (and any addenda) and has no reservations, or has stated them.",
    "The Tenderer's Tender is valid for the period stated in the TDS and Tender Security is attached as required.",
]
for item in std_elig:
    doc.add_paragraph(item, style="List Bullet")

h2("Suggested Technical & Financial Qualification Criteria (Benchmarked Against a Real Comparable Tender)")
note(
    "SOURCING NOTE: The e-GP KB (PPR 2025 / e-GP Guidelines) sets the declaration and process "
    "requirements above but does not specify numeric qualification thresholds for Goods \u2014 "
    "those are package-specific, set by the PE/TEC in the TDS. The World Bank Standard "
    "Procurement Document (Request for Bids \u2014 Goods, One-Envelope, Oct 2017) confirms this is "
    "normal: even that template leaves turnover/experience figures as blank fields for the "
    "borrower to fill in \u2014 there is no universal fixed multiplier. To ground this in real "
    "practice, the structure below is benchmarked against an ACTUAL comparable Bangladeshi "
    "government medical-equipment tender: NICVD (National Institute of Cardiovascular Diseases, "
    "Dhaka) Medical Equipment Tender Schedule, FY2024-2025 (public document, nicvd.gov.bd). "
    "Caveat: that NICVD tender cites Rule 127 of the Public Procurement Rules, 2008 \u2014 it "
    "predates PPR 2025, so it is a real structural precedent from a comparable specialized "
    "government hospital, not a PPR-2025-verified figure. IMPORTANT LIMIT: NICVD's tender "
    "notice does not disclose its own OCE, so no real similar-experience-to-OCE ratio could be "
    "computed from it \u2014 the specific-experience BDT figure below is an illustrative percentage "
    "of NIKDU's OCE (general international procurement norms), not a checked benchmark ratio. "
    "Numeric thresholds (BDT amounts, contract counts) below still require NIKDU/TEC's formal "
    "decision \u2014 setting them too high can unlawfully restrict competition, too low can let "
    "unqualified suppliers through."
)
qual_items = [
    "General experience: minimum 3 (three) years as a registered Supplier of Goods and related services (matches NICVD FY2024-25 precedent, ITT 14.1(a)).",
    "Specific experience: satisfactory completion of supply of similar goods (hemodialysis machines or comparable dialysis/critical-care medical equipment) reaching a minimum aggregate value of approx. BDT 107 crore (illustrative: 40% of the BDT 267.5 crore OCE) achievable through a maximum of 4 (four) contracts, completed within the last 5 (five) years counting backward from the date of IFT publication (structure matches NICVD FY2024-25 precedent, ITT 14.1(b); the 40% figure is NOT derived from NICVD's own ratio \u2014 its tender notice does not disclose an OCE to check against, so no verified ratio could be computed. 40% reflects general international procurement norms, not a checked benchmark. NIKDU/TEC must set the final figure.)",
    "Financial capacity: minimum liquid assets / working capital / credit line(s) from a scheduled Bank of Bangladesh, net of other contractual commitments, of approx. BDT 120-128 crore (1.1-1.2x the specific-experience threshold above, ratio observed in the NICVD FY2024-25 precedent, ITT 15.1(a)) \u2014 not an annual-turnover multiplier. Since the specific-experience base figure itself is illustrative (see above), this derived figure is illustrative too.",
    "Manufacturer's Authorization Form confirming the Tenderer is authorized to supply the offered hemodialysis machines (if the Tenderer is not the manufacturer, a bilateral agreement between manufacturer and bidder is also required \u2014 NICVD FY2024-25 precedent, ITT 21.1(l)).",
    "Regulatory clearance for the offered equipment (DGDA import & medical device clearance for Bangladesh, plus CE/FDA or equivalent from the country of manufacture, per the NICVD precedent's product-certificate requirement).",
    "Demonstrated after-sales service and spare-parts support capability within Bangladesh (own office or authorized local service partner).",
    "No history of debarment under PPR 2025.",
]
for item in qual_items:
    doc.add_paragraph(item, style="List Bullet")

# ================= SECTION 6: PCC =================
doc.add_page_break()
h1("Section 6 \u2014 Particular Conditions of Contract (PCC)")
body(
    "The PCC amends/supplements the fixed GCC clauses [eGP_Guidelines.pdf | page 19]. Entries "
    "to populate when preparing the package:"
)
t6 = doc.add_table(rows=1, cols=2)
t6.style = "Light Grid Accent 1"
hdr = t6.rows[0].cells
hdr[0].text = "GCC Clause Reference"
hdr[1].text = "PCC Entry"
for c in hdr:
    for p in c.paragraphs:
        for r in p.runs:
            r.bold = True
pcc_rows = [
    ("Delivery & Completion", "Delivery to be completed within 180 days of contract signing, in three phases (300 / 400 / 330 units) to hospitals listed in Appendix A (Section 3)"),
    ("Installation & Commissioning", "Supplier responsible for installation, commissioning, and staff training at each delivery site prior to acceptance"),
    ("Inspection & Acceptance", "Inspected and acceptance-tested by NIKDU's Inspection Committee (with biomedical engineering representation) at each delivery site upon installation and commissioning. A Provisional Acceptance Certificate is issued on successful functional testing of each unit; a Final Acceptance Certificate is issued after the warranty-observation period."),
    ("Warranty Period", "Minimum 2 years comprehensive warranty from the date of Final Acceptance at each site \u2014 subject to the Technical Specification Committee's approved figure"),
    ("Payment Terms", "10% advance payment on contract signing (against Advance Payment Guarantee); 80% on delivery, installation and commissioning per phase; 10% retained until Final Acceptance / end of warranty-observation period. Payment due within 30 days of the relevant Acceptance Certificate."),
    ("Liquidated Damages", "0.5% of the value of the delayed/undelivered portion of the Goods per week (or part thereof) of delay beyond the Schedule of Requirements deadline, up to a maximum of 10% of the Contract Price"),
    ("Country of Origin / Manufacturer", "No restriction on country of manufacture, provided it is not an excluded country under the Eligible Countries clause (Section 2) \u2014 currently: all countries except Israel"),
    ("Governing Law", "Laws of the People's Republic of Bangladesh"),
]
for a, b_ in pcc_rows:
    row = t6.add_row().cells
    row[0].text = a
    row[1].text = b_
set_col_widths(t6, [6.0, 10.0])

note(
    "AI-SUGGESTED DEFAULTS \u2014 NOT SOURCED FROM THE e-GP KNOWLEDGE BASE. The KB confirms PPR "
    "2025 requires inspection/acceptance before payment and Performance/Notification-of-Award "
    "timelines tied to Schedule II [PPR2025.pdf | page 207; eGP_Guidelines.pdf | page 26], but "
    "does not specify a numeric Liquidated Damages formula, payment milestone split, or "
    "acceptance protocol for Goods \u2014 those are package-specific PE/TEC decisions. The figures "
    "above (0.5%/week up to 10% cap; 10/80/10 payment split; 30-day payment window) reflect "
    "common PPR/international practice, not a verified legal requirement \u2014 confirm against "
    "NIKDU's standard contract terms before publication."
)

# ================= SECTION 7: ENVELOPE CONTENTS =================
doc.add_page_break()
h1("Section 7 — Envelope Contents (Single Envelope)")
body(
    "This tender follows the One-Stage One-Envelope method [per NIKDU instruction, e-PG4 "
    "[OTM(ICT)]] — technical and financial documents are submitted together in a single "
    "envelope, not split across separate technical and financial envelopes. The Tenderer's "
    "single envelope/submission is expected to contain:"
)

env_items = [
    "Tender Submission Form (Goods) — signed on the Tenderer's letterhead, stating the Tender Price (content basis: PG3-series text [PPR2025.pdf | page 242] — actual submission uses the e-PG4 equivalent form)",
    "Price Schedule(s) — Price and Delivery Schedule for Goods (Manufactured in Bangladesh / to be Imported / already Imported, as applicable) [egp_new_features.md | page 164]",
    "Discount Form, if the Tenderer offers an unconditional discount (content basis: PG3-series text [PPR2025.pdf | page 247])",
    "Tender Security — Pay Order / Bank Draft / Bank Guarantee per the TDS amount and validity [PPR2025.pdf | page 243]",
    "Manufacturer's Authorization Form (plus a bilateral agreement between manufacturer and bidder, if the Tenderer is not the manufacturer — per the NICVD FY2024-25 comparable-tender precedent)",
    "Eligibility declarations and supporting documents: nationality from an eligible country, sole-Tenderer status, no association with the document preparer, no insolvency/debarment record, litigation history, tax and beneficial-ownership declarations (content basis: PG3-series text [PPR2025.pdf | page 244, 249])",
    "Technical Specification compliance/deviation statement, against Section 4",
    "Qualification/experience documents supporting Section 5 (general and specific supply experience, liquid-asset/working-capital evidence, regulatory clearances)",
    "Original product catalogue/brochure and operational/service manual (per the NICVD FY2024-25 comparable-tender precedent)",
    "Manufacturer/Supplier Warranty Certificate (per the NICVD FY2024-25 comparable-tender precedent)",
    "Power of Attorney / authorization of the signatory",
    "Acknowledgment of any Addenda issued to the Tender Document, if applicable",
]
for item in env_items:
    doc.add_paragraph(item, style="List Bullet")

note(
    "FORM-SERIES CAVEAT: This is a document-content checklist, not a form-number checklist. "
    "Joint Venture participation is not applicable here — the e-PG4 [OTM(ICT)] STD does not "
    "permit JV Tenderers [egp_new_features.md | page 163], so no JV-specific forms are listed. "
    "Several items above are substantively based on PG3-series form text (the only Goods "
    "declaration/security/discount text retrievable from the KB) because it is a National "
    "Competitive Tendering STD, NOT the e-PG4 International Competitive Tendering STD this "
    "package requires. Do NOT use PG3-numbered forms for this international tender — NIKDU "
    "must pull the actual e-PG4 form set and form numbers from the e-GP portal when the "
    "package is created there; this list only confirms what content those forms should carry."
)

# ================= SOURCES =================
doc.add_page_break()
h1("Sources")
body(
    "This draft is grounded in the Bangladesh e-GP knowledge base (Bangladesh-only; does not "
    "cover World Bank/ADB donor-funded procurement rules):"
)
sources = [
    "PPR2025.pdf (Public Procurement Rules 2025) \u2014 pages 195, 198, 207, 242, 243, 244, 247, 249, 261, 262",
    "eGP_Guidelines.pdf (e-GP Guidelines 2025 gazette, 12 Mar 2025) \u2014 pages 7, 19-20, 21, 26, 39, 41, 45, 48, 50, 51, 52 (0-indexed; add 1 for the printed page number)",
    "egp_new_features.md \u2014 e-GP module release notes, PPR 2025 rollout entries (SLT calculation, Domestic Preference, JV restrictions, tender security automation)",
    "EXTERNAL (not in the e-GP KB): World Bank Standard Procurement Document \u2014 Request for Bids, Goods (One-Envelope Bidding Process), October 2017 \u2014 Section III, Evaluation and Qualification Criteria (confirms no fixed turnover/experience multiplier; left as a blank template field)",
    "EXTERNAL (not in the e-GP KB): NICVD (National Institute of Cardiovascular Diseases, Dhaka) Medical Equipment Tender Schedule, FY2024-2025, published at nicvd.gov.bd \u2014 real comparable Bangladeshi government medical-equipment tender, cites PPR 2008 (predates PPR 2025); Tender Security clause ITT 31.1 (\"3% of quoted value\") used as a cross-check against NIKDU's TDS Tender Security base",
]
for s in sources:
    doc.add_paragraph(s, style="List Bullet")

doc.add_paragraph()
note(
    "This is a working draft assembled from publicly documented PPR 2025 / e-GP rules, not a "
    "legal or clinical review. Before publication on the e-GP portal, NIKDU should: (1) confirm "
    "the hospital delivery list, (2) have biomedical engineering finalize the technical "
    "specification, (3) have the TEC set numeric qualification thresholds and tender/performance "
    "security amounts, and (4) have the tender validity period and payment/LD terms approved by "
    "the competent authority."
)

footer = doc.add_paragraph()
footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
r = footer.add_run(f"Draft generated {datetime.date.today().isoformat()} \u2014 for NIKDU internal review, not for publication as-is")
r.italic = True
r.font.size = Pt(9)

out_path = r"C:\Users\misla\Documents\BD CONSULTANCY- Procurement Expert\NIKDU-GOB-PE\OUTPUTS\Tender-Documents\NIKDU_ePG4_Hemodialysis_TenderDraft.docx"
doc.save(out_path)
print("Saved:", out_path)
